name: C++ Build and Run

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        ref: ${{ github.head_ref }}

    - name: Use Node.js 20
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install g++
      run: sudo apt-get update && sudo apt-get install -y g++

    - name: Build C++ program
      run: g++ -o my_program main.cpp

    - name: Run C++ program with input from file
      run: ./my_program < input.txt

    - name: Store code as artifact
      uses: actions/upload-artifact@v2
      with:
        name: my_code
        path: main.cpp
